# -*- coding: utf-8 -*-
"""livesession2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bKP1U4iVoXOw_9-MESL8zCPwPeBest_
"""



"""#LIVE SESSIONS ASSIGNMENT 2 

"""



"""#dictionary data struct """

x = {"c":"easy", "python":"moderate", "java":"tough"}
print(x)

x = {"c":"easy", "python":"moderate", "java":"tough"}
print(len(x))

x = {"c":"easy", "python":"moderate", "java":"tough"}
print(x.get("java"))

x = {"c":"easy", "python":"moderate", "java":"tough"}
print(x["java"])

x = {"c":"easy", "python":"moderate", "java":"tough"}
del x["java"]
print(x)

x = {"c":"easy", "python":"moderate", "java":"tough"}
x ["php"] = "cool"
print(x)

x = {"c":"easy", "python":"moderate", "java":"tough"}
x ["php"] = "cool"
x["c++"] = "very mderate"
print(x)

x = {"c":"easy", "python":"moderate", "java":"tough"}
x ["php"] = "cool"
x["c++"] = "very mderate"
x.pop("java")
print(x)

d1 = {"john":40, "peter":45}
d2 = {"john":466, "peter":45}
d1 == d2



"""#OPTIONAL """

n = 5


for i in range(n-1):
    for j in range(i):
        print(' ', end='')
    for k in range(2*(n-i)-1):
        print('*', end='')
    print()

for i in range(n):
    for j in range(n-i-1):
        print(' ', end='')
    for k in range(2*i+1):
        print('*', end='')
    print()

