# -*- coding: utf-8 -*-
"""livesession1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RDXMB5B30D-rrM0zbyWUcdva10_K0RYw

#ASSIGNMENT 1 OF LIVE SESSIONS

#implementing input and print functions
"""

name = input("whats your name ? ")
print (name)

name = input("whats your name ? ")
print("hi " + name)



"""#functions of string from w3schools """

y = "i am aishwarya"
x = y.capitalize()
print(x)

y = "i am aishwarya"

x = y.casefold()

print(x)

y = "i am aishwarya"
x = y.center(20 , "0")

print(x)

y = "i am aishwarya"
x = y.count("a")

print(x)

y = "i am aishwarya"
x = y.encode()

print(x)

y = "i am aishwarya."
x = y.endswith(".")

print(x)

y = "H\te\tl\tl\to"
x =  y.expandtabs(10)

print(x)

y = "i am aishwarya"
x = y.find("am")

print(x)

y = "For only {price:.2f} dollars!"
print(y.format(price = 49))

y = "i am aishwarya"
x = y.index("am")

print(x)

y = "aishwarya7"
x = y.isalnum()

print(x)

y = "i am aishwarya"
x = y.isalpha()

print(x)

y = "i am aishwarya"
x = y.isdecimal()

print(x)

y = "36663667"
x = y.isdigit()

print(x)

y = "i AM aishwarya"
x = y.isidentifier()

print(x)

y = "i am aishwarya"
x = y.islower()

print(x)

y = "6326273676"
x = y.isnumeric()

print(x)

y = "i am aishwarya"
x = y.isprintable()

print(x)

y = "  "
x = y.isspace()

print(x)

y = "I Am Aishwarya"
x = y.istitle()

print(x)

y = "AISHWARYA"
x = y.isupper()

print(x)

y = "banana"
x = y.ljust(2)

print(x, "is my favorite fruit.")

y = "SJJBHKYGUAH"
x = y.lower()

print(x)

y = "     banana     "

x = y.lstrip()

print("of all fruits", x,"is my favorite")

y = "i am aishwarya"

y = "Hello Sam!"
x= y.maketrans("S", "P")
print(y.translate(x))

y = "I could eat bananas all day"

x = y.partition("bananas")

print(x)

y = "I like bananas"

x = y.replace("bananas", "apples")

print(x)

y = "Mi casa, su casa."

x = y.rfind("casa")

print(x)

y = "Mi casa, su casa."

x = y.rfind("casa")

print(x)

y = "Mi casa, su casa."

x = y.rindex("casa")

print(x)

y = "banana"

x = y.rjust(20)

print(x, "is my favorite fruit.")

y = "apple, banana, cherry"

x = y.rsplit(", ")

print(x)

y = "     banana     "

x = y.rstrip()

print("of all fruits", x, "is my favorite")

y = "welcome to the jungle"

x = y.split()

print(x)

y = "Thank you for the music\nWelcome to the jungle"

x = y.splitlines()

print(x)

y = "Hello, welcome to my world."

x = y.startswith("Hello")

print(x)

y = "     banana     "

x = y.strip()

print("of all fruits", x, "is my favorite")

y = "Hello My Name Is PETER"

x = y.swapcase()

print(x)

y = "Welcome to my world"

x = y.title()

print(x)

mydict = {83:  80}
txt = "Hello Sam!"
print(txt.translate(mydict))

y = "Hello my friends"

x = y.upper()

print(x)

y = "50"

x = y.zfill(10)

print(x)



"""#LIST METHODS"""

x = ["c","java","python"]
x.append("c++")
print(x)

x = ["c","java","python"]
x.insert(1,"c++")
print(x)

x = ["c","java","python"]
x.remove("java")
print(x)

x = ["c","java","python"]
x.reverse()
print(x)

x = ["java","c","python"]
x.sort()

print(x)

list = [3, 5, 25, 1, 3]
print(min(list))

fruits = ['apple', 'banana', 'cherry', 'orange']

fruits.clear()
print(fruits)

fruits = ['apple', 'banana', 'cherry', 'orange']

x = fruits.copy()
print(fruits)

fruits = ['apple', 'banana', 'cherry']

x = fruits.count("cherry")
print(fruits)

